[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn -w 1 --timeout 300 'translator.app:app' --log-file -"
healthcheckPath = "/health"
healthcheckTimeout = 600
restartPolicyType = "on_failure"

[variables]
RAILWAY_DEPLOY = "true"
TRANSFORMERS_OFFLINE = "0"